sudo: required
dist: xenial
language: cpp

before_install:
  # Install bats testing suite
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  # Install ZeroMQ
  - sudo apt-get install -y libzmq3-dev libzmq5
  # Install Boost
  - sudo apt-get install -y libboost-all-dev
  # Install yaml-cpp
  - sudo apt-get install -y libyaml-cpp0.5v5 libyaml-cpp-dev
  # Install libcURL
  - sudo apt-get install -y libcurl4-gnutls-dev
  # Install libarchive (to avoid compiling it)
  - sudo apt-get install -y libarchive-dev
  # Install libcap for isolate
  - sudo apt-get install -y libcap-dev
  # Install isolate
  - git clone https://github.com/ioi/isolate.git
  - cd isolate
  - make isolate
  - sudo make install
  - cd ..
  - rm -rf isolate
  # Install coveralls uploader
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest -E tool_ --output-on-failure
  - cd ./judges/recodex_token_judge
  - bats ../../../judges/recodex_token_judge/tests

after_success:
  - ctest -R tool_ --output-on-failure || true
  - cd ${TRAVIS_BUILD_DIR}
  - coveralls -i src --gcov-options '\-lp' > /dev/null
