sudo: required
dist: trusty
language: cpp

before_install:
  # Install ZeroMQ
  - sudo add-apt-repository ppa:chris-lea/zeromq -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libzmq3-dbg libzmq3-dev libzmq3
  # Install yaml-cpp
  - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.2.zip
  - unzip release-0.5.2.zip
  - cd yaml-cpp-release-0.5.2
  - mkdir build;cd build;
  - cmake .. -DBUILD_SHARED_LIBS=1
  - make -j$(nproc)
  - sudo make install
  - cd ../..

install:
  - git submodule update --init

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - tests/run_tests