---  # only one document with all configuration needed
worker-id: 1
worker-description: "linux_worker_1"
broker-uri: "tcp://127.0.0.1:9657"
headers:
    env:
        - bash
        - c-gcc-linux
        - cxx-gcc-linux
        - data-linux
        - freepascal-linux
        - go
        - groovy
        - haskell
        - java
        - kotlin
        - mono
        - node-linux
        - php-linux
        - prolog
        - python3
        - rust
        - scala
    threads: 1
hwgroup: "01-default"
working-directory: "/var/recodex-worker-wd"
file-managers:
    - hostname: "http://127.0.0.1:9999"
      username: "re"    # this must match http auth credentials
      password: "codex" # which are set for fileserver
file-cache:
    cache-dir: "/var/recodex-worker-cache"
logger:
    file: "/var/log/recodex/worker"  # w/o suffix - actual names will be worker.log, worker.1.log, ...
    level: "debug"  # level of logging - one of "debug", "warn", "emerg"
    max-size: 1048576  # 1 MB; max size of file before log rotation
    rotations: 3  # number of rotations kept
limits:
    time: 30            # seconds
    wall-time: 30       # seconds
    extra-time: 2       # seconds
    stack-size: 0       # KiB, but 0 means no special limit
    memory: 1048576     # KiB
    extra-memory: 64    # KiB, will be added to memory limit
    parallel: 0         # if parallel == 1, time and memory limits are merged
    disk-size: 1048576  # KiB
    disk-files: 100
    environ-variable: # environmental variables used inside sandbox
        HOME: /box  # do not change unless you know what are you doing
        PATH: /usr/bin:/bin
        # JAVA_HOME: /path/to/JAVA/jdk  # when JAVA env is enabled
        # LD_LIBRARY_PATH: /usr/local/gcc72/lib64  # e.g., for custom GCC libs
        # PPC_CONFIG_PATH: /usr/etc  # base path for config files in freepascal env
        # GROOVY_HOME: /path/to/groovy/home
      # Python config parameters...
        # PYTHONHASHSEED: 0
        # PYTHONIOENCODING: utf-8
        # VIRTUAL_ENV: /path/to/python/venv
    bound-directories: # All aditional dirs mapped into sandbox (SDKs, libs, venvs, ...)
        - src: "/tmp"
          dst: "/tmp"
          mode: "rw"  # if mode is omitted, dir is mounted as read-only (which is typical for lib dirs)
max-output-length: 4096  # in bytes
max-carboncopy-length: 1048576  # in bytes
cleanup-submission: false  # if true, then folders with data concerning submissions will be cleared after evaluation, should be used carefully, can produce huge amount of used disk space
...
