---  # only one document with all configuration needed
worker-id: 1
broker-uri: tcp://localhost:9657
headers:
    env:
        - c
        - python
    threads: 2
hwgroup: "group1"
file-manager:
    file-collector:
        hostname: "localhost"
        port: 80  # can be ignored in specific modules
        username: ""  # can be ignored in specific modules
        password: ""  # can be ignored in specific modules
    cache:  # only in case that there is cache module
        cache-dir: "/tmp/cache"
logger:
    file: "/tmp/worker"  # w/o suffix - actual names will be worker.log, worker.1.log, ...
    level: "debug"  # level of logging - one of "debug", "warn", "emerg"
    max-size: 1048576  # 1 MB; max size of file before log rotation
    rotations: 3  # number of rotations kept
limits:
    time: 5  # in secs
    wall-time: 6  # seconds
    extra-time: 2  # seconds
    stack-size: 50000  # KB
    memory: 50000  # in KB
    parallel: false  # time and memory limits are merged
    disk-blocks: 50
    disk-inodes: 5
sandboxes-wrap-limits:
    - name: "isolate"
      time: 10  # in seconds
    - name: "csharp"
      time: 20  # in seconds
...
