---  # job which creates directory in /tmp with name: hello_from_codex_worker
submission:
    job-id: hello_evaluation
    language: cpp
    file-collector:
        hostname: http://localhost:9999
        port: 80
        username: ""
        password: ""
tasks:
    - task-id: "mkdir"
      priority: 1
      fatal-failure: false
      cmd:
          bin: "mkdir"
          args:
              - "/tmp/hello_from_codex_worker"
...
