# Hippoes config file
# prerequisites: judge binary in /usr/bin/recodex-judge-normal
#                reachable input and output files - in /tmp/tmpxxxxxx/tasks for our testing file_server.py
# expected result: results.zip uploaded to file server with result file and job log file
#
---  # only one document which contains job, aka. list of tasks and some general infos
submission:  # happy hippoes fence
    job-id: hippoes
    language: c
    file-collector: http://localhost:9999/tasks
    log: true
tasks:
    - task-id: "compilation"
      priority: 2
      fatal-failure: true
      cmd:
          bin: "/usr/bin/gcc"
          args:
              - "solution.c"
              - "-o"
              - "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_1"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "1.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_1"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_1
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.5
                memory: 8192
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_1"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_1
      cmd:
          bin: "fetch"
          args:
              - "1.out"
              - "${SOURCE_DIR}/1.out"
    - task-id: "judging_test_1"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_1
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "1.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_1"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_1
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/1.out"
    - task-id: "fetch_test_2"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "2.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_2"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_2
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.5
                memory: 8192
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_2"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_2
      cmd:
          bin: "fetch"
          args:
              - "2.out"
              - "${SOURCE_DIR}/2.out"
    - task-id: "judging_test_2"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_2
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "2.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_2"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_2
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/2.out"
    - task-id: "fetch_test_3"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "3.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_3"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_3
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.5
                memory: 8192
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_3"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_3
      cmd:
          bin: "fetch"
          args:
              - "3.out"
              - "${SOURCE_DIR}/3.out"
    - task-id: "judging_test_3"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_3
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "3.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_3"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_3
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/3.out"
    - task-id: "fetch_test_4"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "4.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_4"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_4
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.5
                memory: 8192
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_4"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_4
      cmd:
          bin: "fetch"
          args:
              - "4.out"
              - "${SOURCE_DIR}/4.out"
    - task-id: "judging_test_4"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_4
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "4.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_4"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_4
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/4.out"
    - task-id: "fetch_test_5"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "5.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_5"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_5
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.5
                memory: 8192
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_5"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_5
      cmd:
          bin: "fetch"
          args:
              - "5.out"
              - "${SOURCE_DIR}/5.out"
    - task-id: "judging_test_5"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_5
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "5.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_5"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_5
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/5.out"
    - task-id: "fetch_test_6"
      priority: 4
      fatal-failure: false
      dependencies:
          - compilation
      cmd:
          bin: "fetch"
          args:
              - "6.in"
              - "${SOURCE_DIR}/kuly.in"
    - task-id: "evaluation_test_6"
      priority: 5
      fatal-failure: false
      dependencies:
          - fetch_test_6
      cmd:
          bin: "a.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                time: 0.75
                memory: 16384
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "fetch_test_solution_6"
      priority: 6
      fatal-failure: false
      dependencies:
          - evaluation_test_6
      cmd:
          bin: "fetch"
          args:
              - "6.out"
              - "${SOURCE_DIR}/6.out"
    - task-id: "judging_test_6"
      priority: 7
      fatal-failure: false
      dependencies:
          - fetch_test_solution_6
      cmd:
          bin: "${JUDGES_DIR}/recodex-judge-normal"
          args:
              - "6.out"
              - "plot.out"
      sandbox:
          name: "isolate"
          limits:
              - hw-group-id: group1
                parallel: 0
                chdir: ${EVAL_DIR}
                bound-directories:
                    - src: ${SOURCE_DIR}
                      dst: ${EVAL_DIR}
                      mode: RW
    - task-id: "rm_junk_test_6"
      priority: 8
      fatal-failure: false
      dependencies:
          - judging_test_6
      cmd:
          bin: "rm"
          args:
              - "${SOURCE_DIR}/kuly.in"
              - "${SOURCE_DIR}/plot.out"
              - "${SOURCE_DIR}/6.out"
...
